spring:
  security:
    user:
      name: test
      password: 1234

    oauth2:
      client:
        registration:
          facebook:
            client-id: 1145047056243593
            client-secret: 2013f48eff0eacf4d976bd848aaf3345
            scope:
              - public_profile
              - email