server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nongsa?serverTimezone=Asia/Seoul
    username: nongbu
    password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create #update , create, validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
      
  jackson:
    serialization:
      fail-on-empty-beans: false

  profiles:
    include: oauth

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

itemImgLocation: C:/shop/item

uploadPath: file:///C:/shop/

logging.level:
  org.hibernate.SQL: debug

nongsa:
  key: 1234